In [1]:

import pandas as pd

In [2]:
import numpy as np

In [3]:
gizun = pd.read_csv('정리220805.csv')

c:\Users\46861\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py:3552: DtypeWarning: Columns (21) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [4]:
#df['price'] = df['거래금액(만원)'].str.int()

In [5]:
#gizun['거래금액(만원)'].str.lstrip()

In [6]:
gizun.keys()

Index(['아파트코드', '단지명', '시군구', '주소.읍면동.', 'kapt도로명주소', '세대타입.분양형태.', '전용면적(㎡)',
       '계약년월', '층', '건축년도', '주차대수', '좌표X', '좌표Y', '범죄율', '건물연식', '대규모점포_거리',
       '버스정류장_거리', '지하철역_거리', '학교_거리', '유치원_거리', '병원_거리', '거래금액(만원)'],
      dtype='object')

In [20]:
#gizun['거래금액(만원)'][0].str.lstrip()

In [21]:
gizun

아파트코드             단지명            시군구 주소.읍면동.          kapt도로명주소  \
0       A13524004          개포우성3차  서울특별시 강남구 개포동     개포동  서울특별시 강남구 개포로 307   
1       A13524004          개포우성3차  서울특별시 강남구 개포동     개포동  서울특별시 강남구 개포로 307   
2       A13524004          개포우성3차  서울특별시 강남구 개포동     개포동  서울특별시 강남구 개포로 307   
3       A13524004          개포우성3차  서울특별시 강남구 개포동     개포동  서울특별시 강남구 개포로 307   
4       A13524004          개포우성3차  서울특별시 강남구 개포동     개포동  서울특별시 강남구 개포로 307   
...           ...             ...            ...     ...                ...   
725063  A13187702  한신아파트(103~109)  서울특별시 중랑구 중화동     중화동  서울특별시 중랑구 동일로 752   
725064  A13187702  한신아파트(103~109)  서울특별시 중랑구 중화동     중화동  서울특별시 중랑구 동일로 752   
725065  A13187702  한신아파트(103~109)  서울특별시 중랑구 중화동     중화동  서울특별시 중랑구 동일로 752   
725066  A13187702  한신아파트(103~109)  서울특별시 중랑구 중화동     중화동  서울특별시 중랑구 동일로 752   
725067  A13187702  한신아파트(103~109)  서울특별시 중랑구 중화동     중화동  서울특별시 중랑구 동일로 752   

       세대타입.분양형태.  전용면적(㎡)      계약년월     층    건축년도  ...        좌표Y       범죄율  \
0              분양   133.46  201608.0  14.0  1984.0  ...  37.483894  1.370710   
1              분양   104.43  201611.0   7.0  1984.0  ...  37.483894  1.370710   
2              분양   133.46  201611.0   2.0  1984.0  ...  37.483894  1.370710   
3              분양   133.46  201612.0  10.0  1984.0  ...  37.483894  1.370710   
4              분양   161.00  201702.0  12.0  1984.0  ...  37.483894  1.370710   
...           ...      ...       ...   ...     ...  ...        ...       ...   
725063         분양    84.87  201512.0   4.0  1997.0  ...  37.597345  0.947222   
725064         분양    59.76  201512.0   3.0  1997.0  ...  37.597345  0.947222   
725065         분양    84.03  201512.0   9.0  1997.0  ...  37.597345  0.947222   
725066         분양    50.37  201512.0  23.0  1997.0  ...  37.597345  0.947222   
725067         분양    50.37  201512.0  10.0  1997.0  ...  37.597345  0.947222   

        건물연식  대규모점포_거리  버스정류장_거리   지하철역_거리     학교_거리    유치원_거리     병원_거리  \
0       38.0  0.785684  0.098282  0.413746  0.265163  0.350687  0.090105   
1       38.0  0.785684  0.098282  0.413746  0.265163  0.350687  0.090105   
2       38.0  0.785684  0.098282  0.413746  0.265163  0.350687  0.090105   
3       38.0  0.785684  0.098282  0.413746  0.265163  0.350687  0.090105   
4       38.0  0.785684  0.098282  0.413746  0.265163  0.350687  0.090105   
...      ...       ...       ...       ...       ...       ...       ...   
725063   5.0  0.425384  0.187432  0.245853  0.137617  0.075255  0.129186   
725064   5.0  0.425384  0.187432  0.245853  0.137617  0.075255  0.129186   
725065   5.0  0.425384  0.187432  0.245853  0.137617  0.075255  0.129186   
725066   5.0  0.425384  0.187432  0.245853  0.137617  0.075255  0.129186   
725067   5.0  0.425384  0.187432  0.245853  0.137617  0.075255  0.129186   

              거래금액(만원)  
0             136000.0  
1             110000.0  
2             150000.0  
3             130000.0  
4             150000.0  
...                ...  
725063          35,300  
725064          30,000  
725065          37,600  
725066          26,400  
725067          26,000  

[725068 rows x 22 columns]

In [22]:
##for i in gizun.index:
    if type(gizun['거래금액(만원)'][i]) == str:
        gizun['price'] = gizun['거래금액(만원)'].str.replace(',','')
gizun        

IndentationError: unexpected indent (3133800458.py, line 2)

In [ ]:
type(gizun['거래금액(만원)'][0])

float

In [ ]:
type(gizun['거래금액(만원)'][725067])

str

In [298]:
jungu = gizun[gizun['시군구'].str.contains('중구')]

In [303]:
time_df.pop('아파트코드')

0       58.992842
1       58.910861
2       58.764698
3       58.509623
4       58.356006
          ...    
122    100.146663
123    100.256298
124    100.468967
125    100.603285
126    100.638135
Name: 아파트코드, Length: 127, dtype: float64

In [56]:
time_df

Unnamed: 0    년도  월    주택구매력지수   RIR   LIR    계약년월
0             0  2012  1  51.482821  8.32  3.55  201201
1             1  2012  2  51.827810  7.61  3.37  201202
2             2  2012  3  52.139405  8.08  3.63  201203
3             3  2012  4  51.748483  7.84  3.57  201204
4             4  2012  5  52.028382  8.12  3.70  201205
..          ...   ... ..        ...   ...   ...     ...
122         122  2022  3  36.812733   NaN   NaN  202203
123         123  2022  4        NaN   NaN   NaN  202204
124         124  2022  5        NaN   NaN   NaN  202205
125         125  2022  6        NaN   NaN   NaN  202206
126         126  2022  7        NaN   NaN   NaN  202207

[127 rows x 7 columns]

In [301]:
time_df = pd.read_csv('시계열자료1.csv')

In [302]:
time_df

Unnamed: 0       아파트코드    년도  월    주택구매력지수   RIR   LIR    계약년월
0             0   58.992842  2012  1  51.482821  8.32  3.55  201201
1             1   58.910861  2012  2  51.827810  7.61  3.37  201202
2             2   58.764698  2012  3  52.139405  8.08  3.63  201203
3             3   58.509623  2012  4  51.748483  7.84  3.57  201204
4             4   58.356006  2012  5  52.028382  8.12  3.70  201205
..          ...         ...   ... ..        ...   ...   ...     ...
122         122  100.146663  2022  3  36.812733   NaN   NaN  202203
123         123  100.256298  2022  4        NaN   NaN   NaN  202204
124         124  100.468967  2022  5        NaN   NaN   NaN  202205
125         125  100.603285  2022  6        NaN   NaN   NaN  202206
126         126  100.638135  2022  7        NaN   NaN   NaN  202207

[127 rows x 8 columns]

In [299]:
jungu

아파트코드          단지명             시군구 주소.읍면동.            kapt도로명주소  \
91589   A10080701     LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
91590   A10080701     LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
91591   A10080701     LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
91592   A10080701     LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
91593   A10080701     LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
...           ...          ...             ...     ...                  ...   
721875  A10095502  청계천두산위브더제니스    서울특별시 중구 흥인동     흥인동   서울특별시 중구 다산로46길 17   
721876  A10095502  청계천두산위브더제니스    서울특별시 중구 흥인동     흥인동   서울특별시 중구 다산로46길 17   
721877  A10095502  청계천두산위브더제니스    서울특별시 중구 흥인동     흥인동   서울특별시 중구 다산로46길 17   
721878  A10095502  청계천두산위브더제니스    서울특별시 중구 흥인동     흥인동   서울특별시 중구 다산로46길 17   
721879  A10095502  청계천두산위브더제니스    서울특별시 중구 흥인동     흥인동   서울특별시 중구 다산로46길 17   

       세대타입.분양형태.   전용면적(㎡)      계약년월     층    건축년도  ...        좌표Y      범죄율  \
91589          분양   84.9866  201608.0   3.0  2012.0  ...  37.555896  2.59041   
91590          분양   84.9866  201608.0  13.0  2012.0  ...  37.555896  2.59041   
91591          분양   84.9866  201609.0  11.0  2012.0  ...  37.555896  2.59041   
91592          분양   84.9846  201612.0   8.0  2012.0  ...  37.555896  2.59041   
91593          분양   84.9581  201612.0  13.0  2012.0  ...  37.555896  2.59041   
...           ...       ...       ...   ...     ...  ...        ...      ...   
721875         분양  146.9679  201512.0  19.0  2014.0  ...  37.566864  2.59041   
721876         분양  147.3212  201512.0  22.0  2014.0  ...  37.566864  2.59041   
721877         분양  124.2102  201512.0  23.0  2014.0  ...  37.566864  2.59041   
721878         분양  146.9679  201512.0  18.0  2014.0  ...  37.566864  2.59041   
721879         분양  147.3270  201512.0  15.0  2014.0  ...  37.566864  2.59041   

        건물연식  대규모점포_거리  버스정류장_거리   지하철역_거리     학교_거리    유치원_거리     병원_거리  \
91589    4.0  0.056426  0.113172  0.231107  0.126888  0.367897  0.175818   
91590    4.0  0.056426  0.113172  0.231107  0.126888  0.367897  0.175818   
91591    4.0  0.056426  0.113172  0.231107  0.126888  0.367897  0.175818   
91592    4.0  0.056426  0.113172  0.231107  0.126888  0.367897  0.175818   
91593    4.0  0.056426  0.113172  0.231107  0.126888  0.367897  0.175818   
...      ...       ...       ...       ...       ...       ...       ...   
721875   6.0  0.018084  0.192776  0.118238  0.180272  0.217184  0.002898   
721876   6.0  0.018084  0.192776  0.118238  0.180272  0.217184  0.002898   
721877   6.0  0.018084  0.192776  0.118238  0.180272  0.217184  0.002898   
721878   6.0  0.018084  0.192776  0.118238  0.180272  0.217184  0.002898   
721879   6.0  0.018084  0.192776  0.118238  0.180272  0.217184  0.002898   

              거래금액(만원)  
91589          64700.0  
91590          72000.0  
91591          72000.0  
91592          69500.0  
91593          76000.0  
...                ...  
721875          68,494  
721876          67,787  
721877          77,204  
721878          99,020  
721879         102,150  

[12858 rows x 22 columns]

In [304]:
jungu = pd.merge(jungu,time_df,on='계약년월',how='left')

In [305]:
jungu.keys()

Index(['아파트코드', '단지명', '시군구', '주소.읍면동.', 'kapt도로명주소', '세대타입.분양형태.', '전용면적(㎡)',
       '계약년월', '층', '건축년도', '주차대수', '좌표X', '좌표Y', '범죄율', '건물연식', '대규모점포_거리',
       '버스정류장_거리', '지하철역_거리', '학교_거리', '유치원_거리', '병원_거리', '거래금액(만원)',
       'Unnamed: 0', '년도', '월', '주택구매력지수', 'RIR', 'LIR'],
      dtype='object')

In [ ]:
area_df = pd.read_csv('지역자료.csv')

In [ ]:
area_df[area_df['구']=='중구']

Unnamed: 0                        행정구역  201201  201202  201203  201204  \
17          17    서울특별시 중구 소공동(1114052000)   1,224   1,248   1,241   1,252   
18          18    서울특별시 중구 회현동(1114054000)   5,128   5,187   5,191   5,217   
19          19     서울특별시 중구 명동(1114055000)   3,179   3,189   3,189   3,208   
20          20     서울특별시 중구 필동(1114057000)   4,402   4,404   4,391   4,394   
21          21    서울특별시 중구 장충동(1114058000)   5,437   5,437   5,459   5,451   
22          22    서울특별시 중구 광희동(1114059000)   5,360   5,362   5,355   5,337   
23          23   서울특별시 중구 을지로동(1114060500)   1,856   1,862   1,849   1,828   
24          24  서울특별시 중구 신당제5동(1114065000)   9,556   9,855   9,917   9,961   
25          25    서울특별시 중구 황학동(1114067000)  12,209  12,177  12,193  12,221   
26          26    서울특별시 중구 중림동(1114068000)  12,038  12,102  12,195  12,259   

    201205  201206  201207  201208  ...  202201  202202  202203  202204  \
17   1,269   1,272   1,285   1,286  ...   2,252   2,241   2,252   2,263   
18   5,222   5,224   5,218   5,234  ...   4,781   4,749   4,742   4,737   
19   3,213   3,226   3,198   3,174  ...   2,879   2,869   2,849   2,868   
20   4,397   4,379   4,384   4,383  ...   4,007   4,038   4,043   4,019   
21   5,455   5,441   5,430   5,426  ...   4,569   4,578   4,608   4,596   
22   5,338   5,316   5,314   5,298  ...   5,241   5,242   5,244   5,248   
23   1,846   1,853   1,841   1,835  ...   1,743   1,753   1,746   1,737   
24  10,059  10,096  10,165  10,149  ...  10,339  10,326  10,303  10,288   
25  12,184  12,133  12,107  12,104  ...  12,587  12,590  12,623  12,638   
26  12,357  12,497  12,543  12,308  ...  11,976  11,957  11,964  11,968   

    202205  202206  202207   구      동        지리정보  
17   2,261   2,237   2,230  중구    소공동  1114052000  
18   4,735   4,733   4,722  중구    회현동  1114054000  
19   2,877   2,889   2,897  중구     명동  1114055000  
20   4,027   4,036   4,047  중구     필동  1114057000  
21   4,614   4,639   4,664  중구    장충동  1114058000  
22   5,259   5,295   5,289  중구    광희동  1114059000  
23   1,727   1,737   1,739  중구   을지로동  1114060500  
24  10,282  10,284  10,272  중구  신당제5동  1114065000  
25  12,625  12,649  12,643  중구    황학동  1114067000  
26  11,991  11,993  12,024  중구    중림동  1114068000  

[10 rows x 132 columns]

In [ ]:
jungu['주소.읍면동.'].unique()

array(['만리동1가', '만리동2가', '묵정동', '순화동', '신당동', '인현동2가', '중림동', '충무로4가',
       '충무로5가', '황학동', '회현동1가', '회현동2가', '흥인동', '정동'], dtype=object)

In [ ]:
gizun[gizun['시군구']=='중랑구'] 

Empty DataFrame
Columns: [아파트코드, 단지명, 시군구, 주소.읍면동., kapt도로명주소, 세대타입.분양형태., 전용면적(㎡), 계약년월, 층, 건축년도, 주차대수, 좌표X, 좌표Y, 범죄율, 건물연식, 대규모점포_거리, 버스정류장_거리, 지하철역_거리, 학교_거리, 유치원_거리, 병원_거리, 거래금액(만원)]
Index: []

[0 rows x 22 columns]

In [ ]:
area_df[area_df['구']=='중구'] and 

SyntaxError: invalid syntax (375873924.py, line 1)

In [23]:
area_df
area_df = area_df.set_index("동")

In [24]:
area_df

Unnamed: 0                         행정구역  201201  201202  201203  \
동                                                                        
청운효자동           0  서울특별시 종로구 청운효자동(1111051500)  14,933  14,943  14,870   
사직동             1    서울특별시 종로구 사직동(1111053000)   9,759   9,758   9,745   
삼청동             2    서울특별시 종로구 삼청동(1111054000)   3,263   3,251   3,214   
부암동             3    서울특별시 종로구 부암동(1111055000)  11,000  10,967  10,974   
평창동             4    서울특별시 종로구 평창동(1111056000)  19,375  19,406  19,435   
...           ...                          ...     ...     ...     ...   
성내제2동         406  서울특별시 강동구 성내제2동(1174065000)  26,300  26,357  26,385   
성내제3동         407  서울특별시 강동구 성내제3동(1174066000)  25,000  24,994  24,924   
길동            408     서울특별시 강동구 길동(1174068500)  50,558  50,566  50,518   
둔촌제1동         409  서울특별시 강동구 둔촌제1동(1174069000)  20,026  20,087  19,999   
둔촌제2동         410  서울특별시 강동구 둔촌제2동(1174070000)  29,312  29,401  29,379   

       201204  201205  201206  201207  201208  ... 202102.1  202201  202202  \
동                                              ...                            
청운효자동  14,830  14,865  14,839  14,891  14,899  ...   11,978  11,941  11,953   
사직동     9,721   9,710   9,691   9,692   9,639  ...    9,372   9,349   9,362   
삼청동     3,215   3,199   3,231   3,224   3,199  ...    2,456   2,457   2,441   
부암동    10,934  10,932  10,927  10,949  10,933  ...    9,579   9,587   9,541   
평창동    19,414  19,304  19,307  19,351  19,324  ...   18,152  18,134  18,132   
...       ...     ...     ...     ...     ...  ...      ...     ...     ...   
성내제2동  26,359  26,358  26,369  26,371  26,362  ...   23,534  23,465  23,419   
성내제3동  24,934  25,021  25,028  25,016  25,037  ...   23,079  23,033  23,035   
길동     50,478  50,446  50,448  50,432  50,469  ...   45,653  45,610  45,597   
둔촌제1동  20,031  20,006  19,989  19,969  19,964  ...      133     133     132   
둔촌제2동  29,256  29,232  29,209  29,120  29,071  ...   24,661  24,627  24,585   

       202203  202204  202205  202206  202207    구        지리정보  
동                                                               
청운효자동  11,904  11,853  11,838  11,803  11,780  종로구  1111051500  
사직동     9,370   9,334   9,321   9,310   9,292  종로구  1111053000  
삼청동     2,441   2,412   2,390   2,386   2,380  종로구  1111054000  
부암동     9,488   9,476   9,455   9,432   9,423  종로구  1111055000  
평창동    18,087  18,063  18,023  17,963  17,973  종로구  1111056000  
...       ...     ...     ...     ...     ...  ...         ...  
성내제2동  23,403  23,310  23,241  23,199  23,196  강동구  1174065000  
성내제3동  22,975  22,953  22,936  22,941  22,943  강동구  1174066000  
길동     45,554  45,444  45,361  45,342  45,299  강동구  1174068500  
둔촌제1동     132     132     132     132     131  강동구  1174069000  
둔촌제2동  24,529  24,502  24,456  24,371  24,357  강동구  1174070000  

[411 rows x 131 columns]

In [25]:
jungu[1]

KeyError: 1

In [26]:
jungu['인구수']
for i in jungu.index:
    for j in area_df.index:
        if jungu['주소.읍면동.'][i] == area_df['동'][j]:
             jungu['인구수'][i] = area_df[[jungu['주소.읍면동.'][i]],[jungu['계약년월'][i]]]
        if jungu['계약년월'][i] = 
        area_df.filter(regex=jungu['계약년월'][i]).loc
        jungu['인구수'][i] = 

SyntaxError: invalid syntax (1169582688.py, line 6)

In [27]:
import math
jungu['인구수'] = 0
for i in jungu.index:
    a = jungu['계약년월'][i]
    b = str(math.floor(a))
    c = jungu['주소.읍면동.'][i]
    print(b,c)

C:\Users\46861\AppData\Local\Temp\ipykernel_5580\1363797285.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jungu['인구수'] = 0


201608 만리동1가
201608 만리동1가
201609 만리동1가
201612 만리동1가
201612 만리동1가
201612 만리동1가
201612 만리동1가
201701 만리동1가
201704 만리동1가
201704 만리동1가
201705 만리동1가
201705 만리동1가
201705 만리동1가
201705 만리동1가
201705 만리동1가
201705 만리동1가
201705 만리동1가
201706 만리동1가
201706 만리동1가
201706 만리동1가
201706 만리동1가
201707 만리동1가
201707 만리동1가
201707 만리동1가
201705 만리동2가
201612 묵정동
201701 묵정동
201701 묵정동
201705 묵정동
201707 묵정동
201707 묵정동
201707 묵정동
201707 묵정동
201707 묵정동
201707 묵정동
201707 묵정동
201608 순화동
201609 순화동
201609 순화동
201609 순화동
201610 순화동
201610 순화동
201610 순화동
201610 순화동
201610 순화동
201611 순화동
201612 순화동
201612 순화동
201612 순화동
201703 순화동
201610 순화동
201611 순화동
201706 순화동
201707 순화동
201707 순화동
201707 순화동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
201608 신당동
2016

In [28]:
area_df

Unnamed: 0                         행정구역  201201  201202  201203  \
동                                                                        
청운효자동           0  서울특별시 종로구 청운효자동(1111051500)  14,933  14,943  14,870   
사직동             1    서울특별시 종로구 사직동(1111053000)   9,759   9,758   9,745   
삼청동             2    서울특별시 종로구 삼청동(1111054000)   3,263   3,251   3,214   
부암동             3    서울특별시 종로구 부암동(1111055000)  11,000  10,967  10,974   
평창동             4    서울특별시 종로구 평창동(1111056000)  19,375  19,406  19,435   
...           ...                          ...     ...     ...     ...   
성내제2동         406  서울특별시 강동구 성내제2동(1174065000)  26,300  26,357  26,385   
성내제3동         407  서울특별시 강동구 성내제3동(1174066000)  25,000  24,994  24,924   
길동            408     서울특별시 강동구 길동(1174068500)  50,558  50,566  50,518   
둔촌제1동         409  서울특별시 강동구 둔촌제1동(1174069000)  20,026  20,087  19,999   
둔촌제2동         410  서울특별시 강동구 둔촌제2동(1174070000)  29,312  29,401  29,379   

       201204  201205  201206  201207  201208  ... 202102.1  202201  202202  \
동                                              ...                            
청운효자동  14,830  14,865  14,839  14,891  14,899  ...   11,978  11,941  11,953   
사직동     9,721   9,710   9,691   9,692   9,639  ...    9,372   9,349   9,362   
삼청동     3,215   3,199   3,231   3,224   3,199  ...    2,456   2,457   2,441   
부암동    10,934  10,932  10,927  10,949  10,933  ...    9,579   9,587   9,541   
평창동    19,414  19,304  19,307  19,351  19,324  ...   18,152  18,134  18,132   
...       ...     ...     ...     ...     ...  ...      ...     ...     ...   
성내제2동  26,359  26,358  26,369  26,371  26,362  ...   23,534  23,465  23,419   
성내제3동  24,934  25,021  25,028  25,016  25,037  ...   23,079  23,033  23,035   
길동     50,478  50,446  50,448  50,432  50,469  ...   45,653  45,610  45,597   
둔촌제1동  20,031  20,006  19,989  19,969  19,964  ...      133     133     132   
둔촌제2동  29,256  29,232  29,209  29,120  29,071  ...   24,661  24,627  24,585   

       202203  202204  202205  202206  202207    구        지리정보  
동                                                               
청운효자동  11,904  11,853  11,838  11,803  11,780  종로구  1111051500  
사직동     9,370   9,334   9,321   9,310   9,292  종로구  1111053000  
삼청동     2,441   2,412   2,390   2,386   2,380  종로구  1111054000  
부암동     9,488   9,476   9,455   9,432   9,423  종로구  1111055000  
평창동    18,087  18,063  18,023  17,963  17,973  종로구  1111056000  
...       ...     ...     ...     ...     ...  ...         ...  
성내제2동  23,403  23,310  23,241  23,199  23,196  강동구  1174065000  
성내제3동  22,975  22,953  22,936  22,941  22,943  강동구  1174066000  
길동     45,554  45,444  45,361  45,342  45,299  강동구  1174068500  
둔촌제1동     132     132     132     132     131  강동구  1174069000  
둔촌제2동  24,529  24,502  24,456  24,371  24,357  강동구  1174070000  

[411 rows x 131 columns]

In [306]:
jungu

아파트코드          단지명             시군구 주소.읍면동.            kapt도로명주소  \
0      A10080701     LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
1      A10080701     LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
2      A10080701     LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
3      A10080701     LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
4      A10080701     LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
...          ...          ...             ...     ...                  ...   
12853  A10095502  청계천두산위브더제니스    서울특별시 중구 흥인동     흥인동   서울특별시 중구 다산로46길 17   
12854  A10095502  청계천두산위브더제니스    서울특별시 중구 흥인동     흥인동   서울특별시 중구 다산로46길 17   
12855  A10095502  청계천두산위브더제니스    서울특별시 중구 흥인동     흥인동   서울특별시 중구 다산로46길 17   
12856  A10095502  청계천두산위브더제니스    서울특별시 중구 흥인동     흥인동   서울특별시 중구 다산로46길 17   
12857  A10095502  청계천두산위브더제니스    서울특별시 중구 흥인동     흥인동   서울특별시 중구 다산로46길 17   

      세대타입.분양형태.   전용면적(㎡)      계약년월     층    건축년도  ...     학교_거리    유치원_거리  \
0             분양   84.9866  201608.0   3.0  2012.0  ...  0.126888  0.367897   
1             분양   84.9866  201608.0  13.0  2012.0  ...  0.126888  0.367897   
2             분양   84.9866  201609.0  11.0  2012.0  ...  0.126888  0.367897   
3             분양   84.9846  201612.0   8.0  2012.0  ...  0.126888  0.367897   
4             분양   84.9581  201612.0  13.0  2012.0  ...  0.126888  0.367897   
...          ...       ...       ...   ...     ...  ...       ...       ...   
12853         분양  146.9679  201512.0  19.0  2014.0  ...  0.180272  0.217184   
12854         분양  147.3212  201512.0  22.0  2014.0  ...  0.180272  0.217184   
12855         분양  124.2102  201512.0  23.0  2014.0  ...  0.180272  0.217184   
12856         분양  146.9679  201512.0  18.0  2014.0  ...  0.180272  0.217184   
12857         분양  147.3270  201512.0  15.0  2014.0  ...  0.180272  0.217184   

          병원_거리        거래금액(만원)  Unnamed: 0    년도   월    주택구매력지수   RIR   LIR  
0      0.175818         64700.0          55  2016   8  62.082580  7.04  3.06  
1      0.175818         72000.0          55  2016   8  62.082580  7.04  3.06  
2      0.175818         72000.0          56  2016   9  60.222390  7.56  3.24  
3      0.175818         69500.0          59  2016  12  54.946911  7.85  3.58  
4      0.175818         76000.0          59  2016  12  54.946911  7.85  3.58  
...         ...             ...         ...   ...  ..        ...   ...   ...  
12853  0.002898          68,494          47  2015  12  63.157309  7.20  2.99  
12854  0.002898          67,787          47  2015  12  63.157309  7.20  2.99  
12855  0.002898          77,204          47  2015  12  63.157309  7.20  2.99  
12856  0.002898          99,020          47  2015  12  63.157309  7.20  2.99  
12857  0.002898         102,150          47  2015  12  63.157309  7.20  2.99  

[12858 rows x 28 columns]

In [30]:
area_df

Unnamed: 0                         행정구역  201201  201202  201203  \
동                                                                        
청운효자동           0  서울특별시 종로구 청운효자동(1111051500)  14,933  14,943  14,870   
사직동             1    서울특별시 종로구 사직동(1111053000)   9,759   9,758   9,745   
삼청동             2    서울특별시 종로구 삼청동(1111054000)   3,263   3,251   3,214   
부암동             3    서울특별시 종로구 부암동(1111055000)  11,000  10,967  10,974   
평창동             4    서울특별시 종로구 평창동(1111056000)  19,375  19,406  19,435   
...           ...                          ...     ...     ...     ...   
성내제2동         406  서울특별시 강동구 성내제2동(1174065000)  26,300  26,357  26,385   
성내제3동         407  서울특별시 강동구 성내제3동(1174066000)  25,000  24,994  24,924   
길동            408     서울특별시 강동구 길동(1174068500)  50,558  50,566  50,518   
둔촌제1동         409  서울특별시 강동구 둔촌제1동(1174069000)  20,026  20,087  19,999   
둔촌제2동         410  서울특별시 강동구 둔촌제2동(1174070000)  29,312  29,401  29,379   

       201204  201205  201206  201207  201208  ... 202102.1  202201  202202  \
동                                              ...                            
청운효자동  14,830  14,865  14,839  14,891  14,899  ...   11,978  11,941  11,953   
사직동     9,721   9,710   9,691   9,692   9,639  ...    9,372   9,349   9,362   
삼청동     3,215   3,199   3,231   3,224   3,199  ...    2,456   2,457   2,441   
부암동    10,934  10,932  10,927  10,949  10,933  ...    9,579   9,587   9,541   
평창동    19,414  19,304  19,307  19,351  19,324  ...   18,152  18,134  18,132   
...       ...     ...     ...     ...     ...  ...      ...     ...     ...   
성내제2동  26,359  26,358  26,369  26,371  26,362  ...   23,534  23,465  23,419   
성내제3동  24,934  25,021  25,028  25,016  25,037  ...   23,079  23,033  23,035   
길동     50,478  50,446  50,448  50,432  50,469  ...   45,653  45,610  45,597   
둔촌제1동  20,031  20,006  19,989  19,969  19,964  ...      133     133     132   
둔촌제2동  29,256  29,232  29,209  29,120  29,071  ...   24,661  24,627  24,585   

       202203  202204  202205  202206  202207    구        지리정보  
동                                                               
청운효자동  11,904  11,853  11,838  11,803  11,780  종로구  1111051500  
사직동     9,370   9,334   9,321   9,310   9,292  종로구  1111053000  
삼청동     2,441   2,412   2,390   2,386   2,380  종로구  1111054000  
부암동     9,488   9,476   9,455   9,432   9,423  종로구  1111055000  
평창동    18,087  18,063  18,023  17,963  17,973  종로구  1111056000  
...       ...     ...     ...     ...     ...  ...         ...  
성내제2동  23,403  23,310  23,241  23,199  23,196  강동구  1174065000  
성내제3동  22,975  22,953  22,936  22,941  22,943  강동구  1174066000  
길동     45,554  45,444  45,361  45,342  45,299  강동구  1174068500  
둔촌제1동     132     132     132     132     131  강동구  1174069000  
둔촌제2동  24,529  24,502  24,456  24,371  24,357  강동구  1174070000  

[411 rows x 131 columns]

In [31]:
import math
jungu['인구수'] = 0
jungu1 = jungu
for i in jungu.index:
    a = jungu['계약년월'][i]
    b = math.floor(a)
    d = str(b)
    c = jungu['주소.읍면동.'][i]
    try:
        jungu['인구수'][i] = area_df.loc[c,d]
    except:
        print(a)

C:\Users\46861\AppData\Local\Temp\ipykernel_5580\488240900.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jungu['인구수'] = 0
C:\Users\46861\AppData\Local\Temp\ipykernel_5580\488240900.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jungu['인구수'][i] = area_df.loc[c,d]


201608.0
201608.0
201609.0
201612.0
201612.0
201612.0
201612.0
201701.0
201704.0
201704.0
201705.0
201705.0
201705.0
201705.0
201705.0
201705.0
201705.0
201706.0
201706.0
201706.0
201706.0
201707.0
201707.0
201707.0
201705.0
201612.0
201701.0
201701.0
201705.0
201707.0
201707.0
201707.0
201707.0
201707.0
201707.0
201707.0
201608.0
201609.0
201609.0
201609.0
201610.0
201610.0
201610.0
201610.0
201610.0
201611.0
201612.0
201612.0
201612.0
201703.0
201610.0
201611.0
201706.0
201707.0
201707.0
201707.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201608.0
201609.0
201609.0
201609.0
201609.0
201609.0
201609.0
201609.0
201609.0
201609.0
2

In [34]:
jungu['계약년월'][0]

KeyError: 0

In [307]:
jungu.to_csv('중구아파트.csv')

In [35]:
area_df.filter(regex='201601')

201601 201601.1
동                     
청운효자동  13,717   13,801
사직동     9,341    9,681
삼청동     2,798    2,903
부암동    10,450   10,641
평창동    18,860   19,339
...       ...      ...
성내제2동  24,983   25,228
성내제3동  24,669   24,433
길동     50,756   51,231
둔촌제1동  19,003   18,730
둔촌제2동  28,574   28,595

[411 rows x 2 columns]

In [36]:
jungu.loc[[]]

Empty DataFrame
Columns: [아파트코드, 단지명, 시군구, 주소.읍면동., kapt도로명주소, 세대타입.분양형태., 전용면적(㎡), 계약년월, 층, 건축년도, 주차대수, 좌표X, 좌표Y, 범죄율, 건물연식, 대규모점포_거리, 버스정류장_거리, 지하철역_거리, 학교_거리, 유치원_거리, 병원_거리, 거래금액(만원), 인구수]
Index: []

[0 rows x 23 columns]

In [37]:
area_df.loc[[]]

Empty DataFrame
Columns: [Unnamed: 0, 행정구역, 201201, 201202, 201203, 201204, 201205, 201206, 201207, 201208, 201209, 201200, 201201.1, 201202.1, 201301, 201302, 201303, 201304, 201305, 201306, 201307, 201308, 201309, 201300, 201301.1, 201302.1, 201401, 201402, 201403, 201404, 201405, 201406, 201407, 201408, 201409, 201400, 201401.1, 201402.1, 201501, 201502, 201503, 201504, 201505, 201506, 201507, 201508, 201509, 201500, 201501.1, 201502.1, 201601, 201602, 201603, 201604, 201605, 201606, 201607, 201608, 201609, 201600, 201601.1, 201602.1, 201701, 201702, 201703, 201704, 201705, 201706, 201707, 201708, 201709, 201700, 201701.1, 201702.1, 201801, 201802, 201803, 201804, 201805, 201806, 201807, 201808, 201809, 201800, 201801.1, 201802.1, 201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201900, 201901.1, 201902.1, 202001, 202002, ...]
Index: []

[0 rows x 131 columns]

In [38]:
area_df.filter(regex=str(math.floor(jungu['계약년월'][10]))).loc()

KeyError: 10

In [39]:
jungu

아파트코드          단지명             시군구 주소.읍면동.            kapt도로명주소  \
91589   A10080701     LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
91590   A10080701     LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
91591   A10080701     LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
91592   A10080701     LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
91593   A10080701     LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
...           ...          ...             ...     ...                  ...   
721875  A10095502  청계천두산위브더제니스    서울특별시 중구 흥인동     흥인동   서울특별시 중구 다산로46길 17   
721876  A10095502  청계천두산위브더제니스    서울특별시 중구 흥인동     흥인동   서울특별시 중구 다산로46길 17   
721877  A10095502  청계천두산위브더제니스    서울특별시 중구 흥인동     흥인동   서울특별시 중구 다산로46길 17   
721878  A10095502  청계천두산위브더제니스    서울특별시 중구 흥인동     흥인동   서울특별시 중구 다산로46길 17   
721879  A10095502  청계천두산위브더제니스    서울특별시 중구 흥인동     흥인동   서울특별시 중구 다산로46길 17   

       세대타입.분양형태.   전용면적(㎡)      계약년월     층    건축년도  ...      범죄율  건물연식  \
91589          분양   84.9866  201608.0   3.0  2012.0  ...  2.59041   4.0   
91590          분양   84.9866  201608.0  13.0  2012.0  ...  2.59041   4.0   
91591          분양   84.9866  201609.0  11.0  2012.0  ...  2.59041   4.0   
91592          분양   84.9846  201612.0   8.0  2012.0  ...  2.59041   4.0   
91593          분양   84.9581  201612.0  13.0  2012.0  ...  2.59041   4.0   
...           ...       ...       ...   ...     ...  ...      ...   ...   
721875         분양  146.9679  201512.0  19.0  2014.0  ...  2.59041   6.0   
721876         분양  147.3212  201512.0  22.0  2014.0  ...  2.59041   6.0   
721877         분양  124.2102  201512.0  23.0  2014.0  ...  2.59041   6.0   
721878         분양  146.9679  201512.0  18.0  2014.0  ...  2.59041   6.0   
721879         분양  147.3270  201512.0  15.0  2014.0  ...  2.59041   6.0   

        대규모점포_거리  버스정류장_거리   지하철역_거리     학교_거리    유치원_거리     병원_거리  \
91589   0.056426  0.113172  0.231107  0.126888  0.367897  0.175818   
91590   0.056426  0.113172  0.231107  0.126888  0.367897  0.175818   
91591   0.056426  0.113172  0.231107  0.126888  0.367897  0.175818   
91592   0.056426  0.113172  0.231107  0.126888  0.367897  0.175818   
91593   0.056426  0.113172  0.231107  0.126888  0.367897  0.175818   
...          ...       ...       ...       ...       ...       ...   
721875  0.018084  0.192776  0.118238  0.180272  0.217184  0.002898   
721876  0.018084  0.192776  0.118238  0.180272  0.217184  0.002898   
721877  0.018084  0.192776  0.118238  0.180272  0.217184  0.002898   
721878  0.018084  0.192776  0.118238  0.180272  0.217184  0.002898   
721879  0.018084  0.192776  0.118238  0.180272  0.217184  0.002898   

              거래금액(만원)  인구수  
91589          64700.0    0  
91590          72000.0    0  
91591          72000.0    0  
91592          69500.0    0  
91593          76000.0    0  
...                ...  ...  
721875          68,494    0  
721876          67,787    0  
721877          77,204    0  
721878          99,020    0  
721879         102,150    0  

[12858 rows x 23 columns]

In [296]:
jungu

NameError: name 'jungu' is not defined

In [295]:
jungu.to_csv('중구아파트.csv')

NameError: name 'jungu' is not defined

In [60]:
apt_df = jungu[jungu['아파트코드']=='A10080701']

In [61]:
apt_df

아파트코드       단지명             시군구 주소.읍면동.            kapt도로명주소  \
0      A10080701  LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
1      A10080701  LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
2      A10080701  LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
3      A10080701  LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
4      A10080701  LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
...          ...       ...             ...     ...                  ...   
10659  A10080701  LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
10660  A10080701  LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
10661  A10080701  LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
10662  A10080701  LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   
10663  A10080701  LIG서울역리가  서울특별시 중구 만리동1가   만리동1가  서울특별시 중구 만리재로33길 21   

      세대타입.분양형태.  전용면적(㎡)      계약년월     층    건축년도  ...    유치원_거리     병원_거리  \
0             분양  84.9866  201608.0   3.0  2012.0  ...  0.367897  0.175818   
1             분양  84.9866  201608.0  13.0  2012.0  ...  0.367897  0.175818   
2             분양  84.9866  201609.0  11.0  2012.0  ...  0.367897  0.175818   
3             분양  84.9846  201612.0   8.0  2012.0  ...  0.367897  0.175818   
4             분양  84.9581  201612.0  13.0  2012.0  ...  0.367897  0.175818   
...          ...      ...       ...   ...     ...  ...       ...       ...   
10659         분양  84.9846  201504.0   9.0  2012.0  ...  0.367897  0.175818   
10660         분양  84.9866  201505.0   9.0  2012.0  ...  0.367897  0.175818   
10661         분양  84.9566  201509.0   7.0  2012.0  ...  0.367897  0.175818   
10662         분양  84.9788  201511.0  11.0  2012.0  ...  0.367897  0.175818   
10663         분양  84.9866  201512.0   5.0  2012.0  ...  0.367897  0.175818   

             거래금액(만원)  인구수  Unnamed: 0    년도   월    주택구매력지수   RIR   LIR  
0             64700.0    0          55  2016   8  62.082580  7.04  3.06  
1             72000.0    0          55  2016   8  62.082580  7.04  3.06  
2             72000.0    0          56  2016   9  60.222390  7.56  3.24  
3             69500.0    0          59  2016  12  54.946911  7.85  3.58  
4             76000.0    0          59  2016  12  54.946911  7.85  3.58  
...               ...  ...         ...   ...  ..        ...   ...   ...  
10659          61,000    0          39  2015   4  68.097122  6.15  2.69  
10660          64,900    0          40  2015   5  66.300274  6.57  2.83  
10661          65,000    0          44  2015   9  66.842020  6.78  2.83  
10662          62,700    0          46  2015  11  63.660824  7.08  2.80  
10663          68,000    0          47  2015  12  63.157309  7.20  2.99  

[91 rows x 29 columns]

In [89]:
apt_df.keys()

Index(['아파트코드_x', '단지명', '시군구', '주소.읍면동.', 'kapt도로명주소', '세대타입.분양형태.',
       '전용면적(㎡)', '계약년월', '층', '건축년도', '주차대수', '좌표X', '좌표Y', '범죄율', '건물연식',
       '대규모점포_거리', '버스정류장_거리', '지하철역_거리', '학교_거리', '유치원_거리', '병원_거리',
       '거래금액(만원)', 'Unnamed: 0', '아파트코드_y', '년도', '월', '주택구매력지수', 'RIR',
       'LIR'],
      dtype='object')

In [62]:
df = apt_df[['전용면적(㎡)', '계약년월', '건축년도', '주차대수','범죄율', '건물연식',
'대규모점포_거리', '버스정류장_거리', '지하철역_거리', '학교_거리', '유치원_거리', '병원_거리',
'거래금액(만원)','주택구매력지수', 'RIR','LIR']]

In [63]:
df['area']=df['전용면적(㎡)'].round(0)

C:\Users\46861\AppData\Local\Temp\ipykernel_5580\1091362323.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['area']=df['전용면적(㎡)'].round(0)


In [64]:
df.pop('전용면적(㎡)')

0        84.9866
1        84.9866
2        84.9866
3        84.9846
4        84.9581
          ...   
10659    84.9846
10660    84.9866
10661    84.9566
10662    84.9788
10663    84.9866
Name: 전용면적(㎡), Length: 91, dtype: float64

In [65]:
df['area'].unique

<bound method Series.unique of 0        85.0
1        85.0
2        85.0
3        85.0
4        85.0
         ... 
10659    85.0
10660    85.0
10661    85.0
10662    85.0
10663    85.0
Name: area, Length: 91, dtype: float64>

In [66]:
df.astype('float')

ValueError: could not convert string to float: '        66,200'

In [67]:
df['price'] = df['거래금액(만원)'].str.int()


AttributeError: 'StringMethods' object has no attribute 'int'

In [68]:
df

계약년월    건축년도   주차대수      범죄율  건물연식  대규모점포_거리  버스정류장_거리   지하철역_거리  \
0      201608.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
1      201608.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2      201609.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
3      201612.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
4      201612.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
...         ...     ...    ...      ...   ...       ...       ...       ...   
10659  201504.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
10660  201505.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
10661  201509.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
10662  201511.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
10663  201512.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   

          학교_거리    유치원_거리     병원_거리        거래금액(만원)    주택구매력지수   RIR   LIR  \
0      0.126888  0.367897  0.175818         64700.0  62.082580  7.04  3.06   
1      0.126888  0.367897  0.175818         72000.0  62.082580  7.04  3.06   
2      0.126888  0.367897  0.175818         72000.0  60.222390  7.56  3.24   
3      0.126888  0.367897  0.175818         69500.0  54.946911  7.85  3.58   
4      0.126888  0.367897  0.175818         76000.0  54.946911  7.85  3.58   
...         ...       ...       ...             ...        ...   ...   ...   
10659  0.126888  0.367897  0.175818          61,000  68.097122  6.15  2.69   
10660  0.126888  0.367897  0.175818          64,900  66.300274  6.57  2.83   
10661  0.126888  0.367897  0.175818          65,000  66.842020  6.78  2.83   
10662  0.126888  0.367897  0.175818          62,700  63.660824  7.08  2.80   
10663  0.126888  0.367897  0.175818          68,000  63.157309  7.20  2.99   

       area  
0      85.0  
1      85.0  
2      85.0  
3      85.0  
4      85.0  
...     ...  
10659  85.0  
10660  85.0  
10661  85.0  
10662  85.0  
10663  85.0  

[91 rows x 16 columns]

In [107]:
int(df['거래금액(만원)'][0])

64700

In [111]:
df

계약년월    건축년도   주차대수      범죄율  건물연식  대규모점포_거리  버스정류장_거리   지하철역_거리  \
0      201608.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
1      201608.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2      201609.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
3      201612.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
4      201612.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
...         ...     ...    ...      ...   ...       ...       ...       ...   
10659  201504.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
10660  201505.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
10661  201509.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
10662  201511.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
10663  201512.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   

          학교_거리    유치원_거리     병원_거리        거래금액(만원)    주택구매력지수   RIR   LIR  \
0      0.126888  0.367897  0.175818         64700.0  62.082580  7.04  3.06   
1      0.126888  0.367897  0.175818         72000.0  62.082580  7.04  3.06   
2      0.126888  0.367897  0.175818         72000.0  60.222390  7.56  3.24   
3      0.126888  0.367897  0.175818         69500.0  54.946911  7.85  3.58   
4      0.126888  0.367897  0.175818         76000.0  54.946911  7.85  3.58   
...         ...       ...       ...             ...        ...   ...   ...   
10659  0.126888  0.367897  0.175818          61,000  68.097122  6.15  2.69   
10660  0.126888  0.367897  0.175818          64,900  66.300274  6.57  2.83   
10661  0.126888  0.367897  0.175818          65,000  66.842020  6.78  2.83   
10662  0.126888  0.367897  0.175818          62,700  63.660824  7.08  2.80   
10663  0.126888  0.367897  0.175818          68,000  63.157309  7.20  2.99   

       area   price  
0      85.0     NaN  
1      85.0     NaN  
2      85.0     NaN  
3      85.0     NaN  
4      85.0     NaN  
...     ...     ...  
10659  85.0  61,000  
10660  85.0  64,900  
10661  85.0  65,000  
10662  85.0  62,700  
10663  85.0  68,000  

[91 rows x 17 columns]

In [110]:
df['거래금액(만원)'].str.replace(',','')

0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
             ...      
10659            61000
10660            64900
10661            65000
10662            62700
10663            68000
Name: 거래금액(만원), Length: 91, dtype: object

In [71]:
df['price'] = 0
for i in df.index:
    if type(df['거래금액(만원)'][i]) == str:
        df['price'][i] = df['거래금액(만원)'][i].replace(',','')
    else: 
        df['price'][i] = df['거래금액(만원)'][i]
df        

C:\Users\46861\AppData\Local\Temp\ipykernel_5580\2872972236.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price'] = 0
C:\Users\46861\AppData\Local\Temp\ipykernel_5580\2872972236.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price'][i] = df['거래금액(만원)'][i]
C:\Users\46861\AppData\Local\Temp\ipykernel_5580\2872972236.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-co

계약년월    건축년도   주차대수      범죄율  건물연식  대규모점포_거리  버스정류장_거리   지하철역_거리  \
0      201608.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
1      201608.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2      201609.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
3      201612.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
4      201612.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
...         ...     ...    ...      ...   ...       ...       ...       ...   
10659  201504.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
10660  201505.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
10661  201509.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
10662  201511.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
10663  201512.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   

          학교_거리    유치원_거리     병원_거리        거래금액(만원)    주택구매력지수   RIR   LIR  \
0      0.126888  0.367897  0.175818         64700.0  62.082580  7.04  3.06   
1      0.126888  0.367897  0.175818         72000.0  62.082580  7.04  3.06   
2      0.126888  0.367897  0.175818         72000.0  60.222390  7.56  3.24   
3      0.126888  0.367897  0.175818         69500.0  54.946911  7.85  3.58   
4      0.126888  0.367897  0.175818         76000.0  54.946911  7.85  3.58   
...         ...       ...       ...             ...        ...   ...   ...   
10659  0.126888  0.367897  0.175818          61,000  68.097122  6.15  2.69   
10660  0.126888  0.367897  0.175818          64,900  66.300274  6.57  2.83   
10661  0.126888  0.367897  0.175818          65,000  66.842020  6.78  2.83   
10662  0.126888  0.367897  0.175818          62,700  63.660824  7.08  2.80   
10663  0.126888  0.367897  0.175818          68,000  63.157309  7.20  2.99   

       area          price  
0      85.0          64700  
1      85.0          72000  
2      85.0          72000  
3      85.0          69500  
4      85.0          76000  
...     ...            ...  
10659  85.0          61000  
10660  85.0          64900  
10661  85.0          65000  
10662  85.0          62700  
10663  85.0          68000  

[91 rows x 17 columns]

In [72]:
df = df.astype({'price':'float64'})

In [73]:
df.dtypes

계약년월        float64
건축년도        float64
주차대수        float64
범죄율         float64
건물연식        float64
대규모점포_거리    float64
버스정류장_거리    float64
지하철역_거리     float64
학교_거리       float64
유치원_거리      float64
병원_거리       float64
거래금액(만원)     object
주택구매력지수     float64
RIR         float64
LIR         float64
area        float64
price       float64
dtype: object

In [74]:
df['price']=df.groupby(['계약년월'])['price'].transform('mean')

In [75]:
df['price']

0        68350.000000
1        68350.000000
2        72000.000000
3        71075.000000
4        71075.000000
             ...     
10659    61833.333333
10660    64900.000000
10661    65000.000000
10662    62700.000000
10663    68000.000000
Name: price, Length: 91, dtype: float64

In [33]:
pd.to_datetime(df['계약년월'])

0       1970-01-01 00:00:00.000201608
1       1970-01-01 00:00:00.000201608
2       1970-01-01 00:00:00.000201609
3       1970-01-01 00:00:00.000201612
4       1970-01-01 00:00:00.000201612
                     ...             
10659   1970-01-01 00:00:00.000201504
10660   1970-01-01 00:00:00.000201505
10661   1970-01-01 00:00:00.000201509
10662   1970-01-01 00:00:00.000201511
10663   1970-01-01 00:00:00.000201512
Name: 계약년월, Length: 91, dtype: datetime64[ns]

In [76]:
df.pop('거래금액(만원)')

0               64700.0
1               72000.0
2               72000.0
3               69500.0
4               76000.0
              ...      
10659            61,000
10660            64,900
10661            65,000
10662            62,700
10663            68,000
Name: 거래금액(만원), Length: 91, dtype: object

In [77]:
df.dtypes

계약년월        float64
건축년도        float64
주차대수        float64
범죄율         float64
건물연식        float64
대규모점포_거리    float64
버스정류장_거리    float64
지하철역_거리     float64
학교_거리       float64
유치원_거리      float64
병원_거리       float64
주택구매력지수     float64
RIR         float64
LIR         float64
area        float64
price       float64
dtype: object

In [78]:
df1 = df
df1.index.name = '계약년월'

In [79]:
df1.set_index('계약년월')

건축년도   주차대수      범죄율  건물연식  대규모점포_거리  버스정류장_거리   지하철역_거리  \
계약년월                                                                   
201608.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
201608.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
201609.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
201612.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
201612.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
...          ...    ...      ...   ...       ...       ...       ...   
201504.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
201505.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
201509.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
201511.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
201512.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   

             학교_거리    유치원_거리     병원_거리    주택구매력지수   RIR   LIR  area  \
계약년월                                                                  
201608.0  0.126888  0.367897  0.175818  62.082580  7.04  3.06  85.0   
201608.0  0.126888  0.367897  0.175818  62.082580  7.04  3.06  85.0   
201609.0  0.126888  0.367897  0.175818  60.222390  7.56  3.24  85.0   
201612.0  0.126888  0.367897  0.175818  54.946911  7.85  3.58  85.0   
201612.0  0.126888  0.367897  0.175818  54.946911  7.85  3.58  85.0   
...            ...       ...       ...        ...   ...   ...   ...   
201504.0  0.126888  0.367897  0.175818  68.097122  6.15  2.69  85.0   
201505.0  0.126888  0.367897  0.175818  66.300274  6.57  2.83  85.0   
201509.0  0.126888  0.367897  0.175818  66.842020  6.78  2.83  85.0   
201511.0  0.126888  0.367897  0.175818  63.660824  7.08  2.80  85.0   
201512.0  0.126888  0.367897  0.175818  63.157309  7.20  2.99  85.0   

                 price  
계약년월                    
201608.0  68350.000000  
201608.0  68350.000000  
201609.0  72000.000000  
201612.0  71075.000000  
201612.0  71075.000000  
...                ...  
201504.0  61833.333333  
201505.0  64900.000000  
201509.0  65000.000000  
201511.0  62700.000000  
201512.0  68000.000000  

[91 rows x 15 columns]

In [80]:
df1.to_csv('한아파트대상lstm.csv')

In [6]:
!pip install pandas

     ---------------------------------------- 10.0/10.0 MB 7.2 MB/s eta 0:00:00
  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)


여기서부터 시작해도됨

In [1]:
import pandas as pd
df1 = pd.read_csv('한아파트대상lstm.csv')
df1

계약년월    계약년월.1    건축년도   주차대수      범죄율  건물연식  대규모점포_거리  버스정류장_거리  \
0       0  201608.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
1       1  201608.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2       2  201609.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
3       3  201612.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
4       4  201612.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
..    ...       ...     ...    ...      ...   ...       ...       ...   
86  10659  201504.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
87  10660  201505.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
88  10661  201509.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
89  10662  201511.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
90  10663  201512.0  2012.0  221.0  2.59041   4.0  0.056426  0.113172   

     지하철역_거리     학교_거리    유치원_거리     병원_거리    주택구매력지수   RIR   LIR  area  \
0   0.231107  0.126888  0.367897  0.175818  62.082580  7.04  3.06  85.0   
1   0.231107  0.126888  0.367897  0.175818  62.082580  7.04  3.06  85.0   
2   0.231107  0.126888  0.367897  0.175818  60.222390  7.56  3.24  85.0   
3   0.231107  0.126888  0.367897  0.175818  54.946911  7.85  3.58  85.0   
4   0.231107  0.126888  0.367897  0.175818  54.946911  7.85  3.58  85.0   
..       ...       ...       ...       ...        ...   ...   ...   ...   
86  0.231107  0.126888  0.367897  0.175818  68.097122  6.15  2.69  85.0   
87  0.231107  0.126888  0.367897  0.175818  66.300274  6.57  2.83  85.0   
88  0.231107  0.126888  0.367897  0.175818  66.842020  6.78  2.83  85.0   
89  0.231107  0.126888  0.367897  0.175818  63.660824  7.08  2.80  85.0   
90  0.231107  0.126888  0.367897  0.175818  63.157309  7.20  2.99  85.0   

           price  
0   68350.000000  
1   68350.000000  
2   72000.000000  
3   71075.000000  
4   71075.000000  
..           ...  
86  61833.333333  
87  64900.000000  
88  65000.000000  
89  62700.000000  
90  68000.000000  

[91 rows x 17 columns]

In [2]:
df1['계약년월.1']=df1['계약년월.1'].astype(int)

In [3]:
df1['계약년월.1']=pd.to_datetime(df1['계약년월.1'],format='%Y%m')

In [4]:
df1.pop('계약년월')

0         0
1         1
2         2
3         3
4         4
      ...  
86    10659
87    10660
88    10661
89    10662
90    10663
Name: 계약년월, Length: 91, dtype: int64

In [5]:
df1

계약년월.1    건축년도   주차대수      범죄율  건물연식  대규모점포_거리  버스정류장_거리   지하철역_거리  \
0  2016-08-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
1  2016-08-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2  2016-09-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
3  2016-12-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
4  2016-12-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
..        ...     ...    ...      ...   ...       ...       ...       ...   
86 2015-04-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
87 2015-05-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
88 2015-09-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
89 2015-11-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
90 2015-12-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   

       학교_거리    유치원_거리     병원_거리    주택구매력지수   RIR   LIR  area         price  
0   0.126888  0.367897  0.175818  62.082580  7.04  3.06  85.0  68350.000000  
1   0.126888  0.367897  0.175818  62.082580  7.04  3.06  85.0  68350.000000  
2   0.126888  0.367897  0.175818  60.222390  7.56  3.24  85.0  72000.000000  
3   0.126888  0.367897  0.175818  54.946911  7.85  3.58  85.0  71075.000000  
4   0.126888  0.367897  0.175818  54.946911  7.85  3.58  85.0  71075.000000  
..       ...       ...       ...        ...   ...   ...   ...           ...  
86  0.126888  0.367897  0.175818  68.097122  6.15  2.69  85.0  61833.333333  
87  0.126888  0.367897  0.175818  66.300274  6.57  2.83  85.0  64900.000000  
88  0.126888  0.367897  0.175818  66.842020  6.78  2.83  85.0  65000.000000  
89  0.126888  0.367897  0.175818  63.660824  7.08  2.80  85.0  62700.000000  
90  0.126888  0.367897  0.175818  63.157309  7.20  2.99  85.0  68000.000000  

[91 rows x 16 columns]

In [6]:
df1 = df1.set_index('계약년월.1')
df1

건축년도   주차대수      범죄율  건물연식  대규모점포_거리  버스정류장_거리   지하철역_거리  \
계약년월.1                                                                   
2016-08-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2016-08-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2016-09-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2016-12-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2016-12-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
...            ...    ...      ...   ...       ...       ...       ...   
2015-04-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2015-05-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2015-09-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2015-11-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2015-12-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   

               학교_거리    유치원_거리     병원_거리    주택구매력지수   RIR   LIR  area  \
계약년월.1                                                                  
2016-08-01  0.126888  0.367897  0.175818  62.082580  7.04  3.06  85.0   
2016-08-01  0.126888  0.367897  0.175818  62.082580  7.04  3.06  85.0   
2016-09-01  0.126888  0.367897  0.175818  60.222390  7.56  3.24  85.0   
2016-12-01  0.126888  0.367897  0.175818  54.946911  7.85  3.58  85.0   
2016-12-01  0.126888  0.367897  0.175818  54.946911  7.85  3.58  85.0   
...              ...       ...       ...        ...   ...   ...   ...   
2015-04-01  0.126888  0.367897  0.175818  68.097122  6.15  2.69  85.0   
2015-05-01  0.126888  0.367897  0.175818  66.300274  6.57  2.83  85.0   
2015-09-01  0.126888  0.367897  0.175818  66.842020  6.78  2.83  85.0   
2015-11-01  0.126888  0.367897  0.175818  63.660824  7.08  2.80  85.0   
2015-12-01  0.126888  0.367897  0.175818  63.157309  7.20  2.99  85.0   

                   price  
계약년월.1                    
2016-08-01  68350.000000  
2016-08-01  68350.000000  
2016-09-01  72000.000000  
2016-12-01  71075.000000  
2016-12-01  71075.000000  
...                  ...  
2015-04-01  61833.333333  
2015-05-01  64900.000000  
2015-09-01  65000.000000  
2015-11-01  62700.000000  
2015-12-01  68000.000000  

[91 rows x 15 columns]

In [7]:
df1 = df1.loc[~df1.index.duplicated(keep='first')]

In [8]:
df1.index

DatetimeIndex(['2016-08-01', '2016-09-01', '2016-12-01', '2017-01-01',
               '2017-04-01', '2017-05-01', '2017-06-01', '2017-07-01',
               '2016-01-01', '2016-02-01', '2016-04-01', '2016-05-01',
               '2016-06-01', '2016-07-01', '2019-04-01', '2019-06-01',
               '2019-07-01', '2020-11-01', '2021-01-01', '2012-04-01',
               '2012-05-01', '2013-05-01', '2013-06-01', '2013-08-01',
               '2013-10-01', '2013-11-01', '2013-12-01', '2014-02-01',
               '2014-08-01', '2015-01-01', '2015-02-01', '2015-03-01',
               '2015-04-01', '2015-05-01', '2015-09-01', '2015-11-01',
               '2015-12-01'],
              dtype='datetime64[ns]', name='계약년월.1', freq=None)

In [9]:
df1 = df1.sort_index(ascending=True)

In [10]:
df1

건축년도   주차대수      범죄율  건물연식  대규모점포_거리  버스정류장_거리   지하철역_거리  \
계약년월.1                                                                   
2012-04-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2012-05-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2013-05-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2013-06-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2013-08-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2013-10-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2013-11-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2013-12-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2014-02-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2014-08-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2015-01-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2015-02-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2015-03-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2015-04-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2015-05-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2015-09-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2015-11-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2015-12-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2016-01-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2016-02-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2016-04-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2016-05-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2016-06-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2016-07-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2016-08-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2016-09-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2016-12-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2017-01-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2017-04-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2017-05-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2017-06-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2017-07-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2019-04-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2019-06-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2019-07-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2020-11-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   
2021-01-01  2012.0  221.0  2.59041   4.0  0.056426  0.113172  0.231107   

               학교_거리    유치원_거리     병원_거리    주택구매력지수   RIR   LIR  area  \
계약년월.1                                                                  
2012-04-01  0.126888  0.367897  0.175818  51.748483  7.84  3.57  85.0   
2012-05-01  0.126888  0.367897  0.175818  52.028382  8.12  3.70  85.0   
2013-05-01  0.126888  0.367897  0.175818  62.214539  7.52  3.69  85.0   
2013-06-01  0.126888  0.367897  0.175818  62.625675  7.26  3.64  85.0   
2013-08-01  0.126888  0.367897  0.175818  65.001439  6.73  3.36  85.0   
2013-10-01  0.126888  0.367897  0.175818  64.428067  6.49  3.26  85.0   
2013-11-01  0.126888  0.367897  0.175818  64.615202  6.41  3.14  85.0   
2013-12-01  0.126888  0.367897  0.175818  64.767020  6.82  3.13  85.0   
2014-02-01  0.126888  0.367897  0.175818  66.227445  6.51  2.70  85.0   
2014-08-01  0.126888  0.367897  0.175818  67.882685  7.38  2.86  85.0   
2015-01-01  0.126888  0.367897  0.175818  68.545529  6.69  2.74  85.0   
2015-02-01  0.126888  0.367897  0.175818  68.473754  6.62  2.76  85.0   
2015-03-01  0.126888  0.367897  0.175818  69.803858  6.49  2.84  85.0   
2015-04-01  0.126888  0.367897  

In [11]:
df1.shape

(37, 15)

In [76]:
df1.to_csv('price.csv')

여기서 시작2

In [268]:
df1 = pd.read_csv('price.csv',header=0,index_col=0)

In [269]:
df1 = df1[['price','건축년도','주차대수','범죄율','건물연식','대규모점포_거리','버스정류장_거리','지하철역_거리','학교_거리','유치원_거리','병원_거리','주택구매력지수','RIR','LIR','area']]
df1

price    건축년도   주차대수      범죄율  건물연식  대규모점포_거리  버스정류장_거리  \
계약년월.1                                                                        
2012-04-01   66200.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2012-05-01   64300.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2013-05-01   53166.666667  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2013-06-01   52500.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2013-08-01   53000.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2013-10-01   57500.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2013-11-01   59000.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2013-12-01   53900.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2014-02-01   58000.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2014-08-01   56500.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2015-01-01   55000.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2015-02-01   55000.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2015-03-01   62500.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2015-04-01   61833.333333  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2015-05-01   64900.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2015-09-01   65000.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2015-11-01   62700.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2015-12-01   68000.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2016-01-01   61250.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2016-02-01   62533.333333  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2016-04-01   65250.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2016-05-01   65800.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2016-06-01   70000.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2016-07-01   70500.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2016-08-01   68350.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2016-09-01   72000.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2016-12-01   71075.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2017-01-01   68700.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2017-04-01   69900.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2017-05-01   69785.714286  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2017-06-01   76000.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2017-07-01   74000.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2019-04-01  104700.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2019-06-01   96416.666667  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2019-07-01   98166.666667  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2020-11-01  145000.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   
2021-01-01  160000.000000  2012.0  221.0  2.59041   4.0  0.056426  0.113172   

             지하철역_거리     학교_거리    유치원_거리     병원_거리    주택구매력지수   RIR   LIR  \
계약년월.1                                                                      
2012-04-01  0.231107  0.126888  0.367897  0.175818  51.748483  7.84  3.57   
2012-05-01  0.231107  0.126888  0.367897  0.175818  52.028382  8.12  3.70   
2013-05-01  0.231107  0.126888  0.367897  0.175818  62.214539  7.52  3.69   
2013-06-01  0.231107  0.126888  0.367897  0.175818  62.625675  7.26  3.64   
2013-08-01  0.231107  0.126888  0.367897  0.175818  65.001439  6.73  3.36   
2013-10-01  0.231107  0.126888  0.367897  0.175818  64.428067  6.49  3.26   
2013-11-01  0.231107  0.126888  0.367897  0.175818  64.615202  6.41  3.14   
2013-12-01  0.231107  0.126888  0.367897  0.175818  64.767020  6.82  3.13   
2014-02-01  0.231107  0.126888  0.367897  0.175818  66.227445  6.51  2.70   
2014-08-01  0.231107  0.126888  0.367897  0.175818  67.882685  7.38  2.86   
2015-01-01  0.

In [270]:
values = df1.values

In [271]:
values

array([[6.62000000e+04, 2.01200000e+03, 2.21000000e+02, 2.59040994e+00,
        4.00000000e+00, 5.64261070e-02, 1.13171643e-01, 2.31107338e-01,
        1.26888369e-01, 3.67897484e-01, 1.75817914e-01, 5.17484830e+01,
        7.84000000e+00, 3.57000000e+00, 8.50000000e+01],
       [6.43000000e+04, 2.01200000e+03, 2.21000000e+02, 2.59040994e+00,
        4.00000000e+00, 5.64261070e-02, 1.13171643e-01, 2.31107338e-01,
        1.26888369e-01, 3.67897484e-01, 1.75817914e-01, 5.20283820e+01,
        8.12000000e+00, 3.70000000e+00, 8.50000000e+01],
       [5.31666667e+04, 2.01200000e+03, 2.21000000e+02, 2.59040994e+00,
        4.00000000e+00, 5.64261070e-02, 1.13171643e-01, 2.31107338e-01,
        1.26888369e-01, 3.67897484e-01, 1.75817914e-01, 6.22145391e+01,
        7.52000000e+00, 3.69000000e+00, 8.50000000e+01],
       [5.25000000e+04, 2.01200000e+03, 2.21000000e+02, 2.59040994e+00,
        4.00000000e+00, 5.64261070e-02, 1.13171643e-01, 2.31107338e-01,
        1.26888369e-01, 3.67897484e-0

In [272]:
values.shape

(37, 15)

In [273]:
df1.shape

(37, 15)

In [274]:
values

array([[6.62000000e+04, 2.01200000e+03, 2.21000000e+02, 2.59040994e+00,
        4.00000000e+00, 5.64261070e-02, 1.13171643e-01, 2.31107338e-01,
        1.26888369e-01, 3.67897484e-01, 1.75817914e-01, 5.17484830e+01,
        7.84000000e+00, 3.57000000e+00, 8.50000000e+01],
       [6.43000000e+04, 2.01200000e+03, 2.21000000e+02, 2.59040994e+00,
        4.00000000e+00, 5.64261070e-02, 1.13171643e-01, 2.31107338e-01,
        1.26888369e-01, 3.67897484e-01, 1.75817914e-01, 5.20283820e+01,
        8.12000000e+00, 3.70000000e+00, 8.50000000e+01],
       [5.31666667e+04, 2.01200000e+03, 2.21000000e+02, 2.59040994e+00,
        4.00000000e+00, 5.64261070e-02, 1.13171643e-01, 2.31107338e-01,
        1.26888369e-01, 3.67897484e-01, 1.75817914e-01, 6.22145391e+01,
        7.52000000e+00, 3.69000000e+00, 8.50000000e+01],
       [5.25000000e+04, 2.01200000e+03, 2.21000000e+02, 2.59040994e+00,
        4.00000000e+00, 5.64261070e-02, 1.13171643e-01, 2.31107338e-01,
        1.26888369e-01, 3.67897484e-0

In [275]:
values.shape

(37, 15)

In [276]:
from sklearn import preprocessing
from sklearn.metrics import mean_squared_error


스케일링

In [277]:
values = values.astype('float32')

In [278]:
values

array([[6.62000000e+04, 2.01200000e+03, 2.21000000e+02, 2.59040999e+00,
        4.00000000e+00, 5.64261079e-02, 1.13171645e-01, 2.31107339e-01,
        1.26888365e-01, 3.67897481e-01, 1.75817907e-01, 5.17484818e+01,
        7.84000015e+00, 3.56999993e+00, 8.50000000e+01],
       [6.43000000e+04, 2.01200000e+03, 2.21000000e+02, 2.59040999e+00,
        4.00000000e+00, 5.64261079e-02, 1.13171645e-01, 2.31107339e-01,
        1.26888365e-01, 3.67897481e-01, 1.75817907e-01, 5.20283813e+01,
        8.11999989e+00, 3.70000005e+00, 8.50000000e+01],
       [5.31666680e+04, 2.01200000e+03, 2.21000000e+02, 2.59040999e+00,
        4.00000000e+00, 5.64261079e-02, 1.13171645e-01, 2.31107339e-01,
        1.26888365e-01, 3.67897481e-01, 1.75817907e-01, 6.22145386e+01,
        7.51999998e+00, 3.69000006e+00, 8.50000000e+01],
       [5.25000000e+04, 2.01200000e+03, 2.21000000e+02, 2.59040999e+00,
        4.00000000e+00, 5.64261079e-02, 1.13171645e-01, 2.31107339e-01,
        1.26888365e-01, 3.67897481e-0

In [279]:
scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
scaled = scaler.fit_transform(values)

In [280]:
def series_to_supervised(data, n_in=1, n_out=1, dropnan=True):
  n_vars = 1 if type(data) is list else data.shape[1]
  df = pd.DataFrame(data)
  cols, names = list(), list()
  # input sequence (t-n, ... t-1)
  for i in range(n_in, 0, -1):
      cols.append(df.shift(i))
      names += [('var%d(t-%d)' % (j+1, i)) for j in range(n_vars)]
  # forecast sequence (t, t+1, ... t+n)
  for i in range(0, n_out):
      cols.append(df.shift(-i))
      if i == 0:
          names += [('var%d(t)' % (j+1)) for j in range(n_vars)]
      else:
          names += [('var%d(t+%d)' % (j+1, i)) for j in range(n_vars)]
  # put it all together
  agg = pd.concat(cols, axis=1)
  agg.columns = names
  # drop rows with NaN values
  if dropnan:
      agg.dropna(inplace=True)
  return agg

In [281]:
scaled.shape

(37, 15)

the shape of the scaled dataframe is (n) x (m)
The particular call to series_to_supervised() in line 50 implies that the scaled dataframe will be reshaped into a (n-1) x (2m)

In [326]:
reframed = series_to_supervised(scaled, 1, 1)

In [327]:
reframed.shape

(36, 30)

In [328]:
print(reframed)

    var1(t-1)  var2(t-1)  var3(t-1)  var4(t-1)  var5(t-1)  var6(t-1)  \
1    0.127442        0.0        0.0        0.0        0.0        0.0   
2    0.109767        0.0        0.0        0.0        0.0        0.0   
3    0.006202        0.0        0.0        0.0        0.0        0.0   
4    0.000000        0.0        0.0        0.0        0.0        0.0   
5    0.004651        0.0        0.0        0.0        0.0        0.0   
6    0.046512        0.0        0.0        0.0        0.0        0.0   
7    0.060465        0.0        0.0        0.0        0.0        0.0   
8    0.013023        0.0        0.0        0.0        0.0        0.0   
9    0.051163        0.0        0.0        0.0        0.0        0.0   
10   0.037209        0.0        0.0        0.0        0.0        0.0   
11   0.023256        0.0        0.0        0.0        0.0        0.0   
12   0.023256        0.0        0.0        0.0        0.0        0.0   
13   0.093023        0.0        0.0        0.0        0.0       

In [329]:
reframed.columns[29]

'var15(t)'

In [330]:
reframed.columns[15]

'var1(t)'

In [286]:
#(n-1) x (m+1) = 36 x 16
#14컬럼 제거
#n x m = 37 x 15
#(n-1) x (2m) = 36 x 30

In [287]:
reframed.drop(reframed.columns[[16,17,18,19,20,21,22,23,24,25,26,27,28,29]], axis=1, inplace=True)

In [288]:
reframed

var1(t-1)  var2(t-1)  var3(t-1)  var4(t-1)  var5(t-1)  var6(t-1)  \
1    0.127442        0.0        0.0        0.0        0.0        0.0   
2    0.109767        0.0        0.0        0.0        0.0        0.0   
3    0.006202        0.0        0.0        0.0        0.0        0.0   
4    0.000000        0.0        0.0        0.0        0.0        0.0   
5    0.004651        0.0        0.0        0.0        0.0        0.0   
6    0.046512        0.0        0.0        0.0        0.0        0.0   
7    0.060465        0.0        0.0        0.0        0.0        0.0   
8    0.013023        0.0        0.0        0.0        0.0        0.0   
9    0.051163        0.0        0.0        0.0        0.0        0.0   
10   0.037209        0.0        0.0        0.0        0.0        0.0   
11   0.023256        0.0        0.0        0.0        0.0        0.0   
12   0.023256        0.0        0.0        0.0        0.0        0.0   
13   0.093023        0.0        0.0        0.0        0.0        0.0   
14   0.086822        0.0        0.0        0.0        0.0        0.0   
15   0.115349        0.0        0.0        0.0        0.0        0.0   
16   0.116279        0.0        0.0        0.0        0.0        0.0   
17   0.094884        0.0        0.0        0.0        0.0        0.0   
18   0.144186        0.0        0.0        0.0        0.0        0.0   
19   0.081395        0.0        0.0        0.0        0.0        0.0   
20   0.093333        0.0        0.0        0.0        0.0        0.0   
21   0.118605        0.0        0.0        0.0        0.0        0.0   
22   0.123721        0.0        0.0        0.0        0.0        0.0   
23   0.162791        0.0        0.0        0.0        0.0        0.0   
24   0.167442        0.0        0.0        0.0        0.0        0.0   
25   0.147442        0.0        0.0        0.0        0.0        0.0   
26   0.181395        0.0        0.0        0.0        0.0        0.0   
27   0.172791        0.0        0.0        0.0        0.0        0.0   
28   0.150698        0.0        0.0        0.0        0.0        0.0   
29   0.161860        0.0        0.0        0.0        0.0        0.0   
30   0.160797        0.0        0.0        0.0        0.0        0.0   
31   0.218605        0.0        0.0        0.0        0.0        0.0   
32   0.200000        0.0        0.0        0.0        0.0        0.0   
33   0.485581        0.0        0.0        0.0        0.0        0.0   
34   0.408527        0.0        0.0        0.0        0.0        0.0   
35   0.424806        0.0        0.0        0.0        0.0        0.0   
36   0.860465        0.0        0.0        0.0        0.0        0.0   

    var7(t-1)  var8(t-1)  var9(t-1)  var10(t-1)  var11(t-1)  var12(t-1)  \
1         0.0        0.0        0.0         0.0         0.0    0.346095   
2         0.0        0.0        0.0         0.0         0.0    0.356233   
3         0.0        0.0        0.0         0.0         0.0    0.725141   
4         0.0        0.0        0.0         0.0         0.0    0.740031   
5         0.0        0.0        0.0         0.0         0.0    0.826073   
6         0.0        0.0        0.0         0.0         0.0    0.805307   
7         0.0        0.0        0.0         0.0         0.0    0.812085   
8         0.0        0.0        0.0         0.0         0.0    0.817583   
9         0.0        0.0        0.0         0.0         0.0    0.870475   
10        0.0        0.0        0.0         0.0         0.0    0.930422   
11        0.0        0.0        0.0         0.0         0.0    0.954428   
12        0.0        0.0        0.0         0.0         0.0    0.951828   
13        0.0        0.0        0.0         0.0         0.0    1.000000   
14        0.0        0.0        0.0         0.0         0.0    0.938188   
15        0.0        0.0        0.0         0.0         0.0    0.873112   
16        0.0        0.0        0.0         0.0         0.0    0.892732   
17        0.0        0.0        0.0         0.0         0.0    0

In [289]:
values

array([[6.62000000e+04, 2.01200000e+03, 2.21000000e+02, 2.59040999e+00,
        4.00000000e+00, 5.64261079e-02, 1.13171645e-01, 2.31107339e-01,
        1.26888365e-01, 3.67897481e-01, 1.75817907e-01, 5.17484818e+01,
        7.84000015e+00, 3.56999993e+00, 8.50000000e+01],
       [6.43000000e+04, 2.01200000e+03, 2.21000000e+02, 2.59040999e+00,
        4.00000000e+00, 5.64261079e-02, 1.13171645e-01, 2.31107339e-01,
        1.26888365e-01, 3.67897481e-01, 1.75817907e-01, 5.20283813e+01,
        8.11999989e+00, 3.70000005e+00, 8.50000000e+01],
       [5.31666680e+04, 2.01200000e+03, 2.21000000e+02, 2.59040999e+00,
        4.00000000e+00, 5.64261079e-02, 1.13171645e-01, 2.31107339e-01,
        1.26888365e-01, 3.67897481e-01, 1.75817907e-01, 6.22145386e+01,
        7.51999998e+00, 3.69000006e+00, 8.50000000e+01],
       [5.25000000e+04, 2.01200000e+03, 2.21000000e+02, 2.59040999e+00,
        4.00000000e+00, 5.64261079e-02, 1.13171645e-01, 2.31107339e-01,
        1.26888365e-01, 3.67897481e-0

데이터에 따라 수정해야됨 train 길이

In [290]:
values = reframed.values
n_train_hours =  24 #테스트 데이터 얼마나 사용할 건지
train = values[:n_train_hours, :]
test = values[n_train_hours:, :]
# split into input and outputs
train_X, train_y = train[:, :-1], train[:, -1]
test_X, test_y = test[:, :-1], test[:, -1]
# reshape input to be 3D [samples, timesteps, features]
train_X = train_X.reshape((train_X.shape[0], 1, train_X.shape[1]))
test_X = test_X.reshape((test_X.shape[0], 1, test_X.shape[1]))

In [291]:
train_y

array([0.10976744, 0.00620157, 0.        , 0.00465116, 0.04651165,
       0.0604651 , 0.01302326, 0.05116278, 0.03720927, 0.02325583,
       0.02325583, 0.09302324, 0.08682168, 0.11534882, 0.11627907,
       0.09488374, 0.14418602, 0.08139533, 0.0933333 , 0.11860466,
       0.12372094, 0.16279072, 0.16744184, 0.14744186], dtype=float32)

In [292]:
test_y

array([0.18139535, 0.1727907 , 0.15069765, 0.16186047, 0.1607973 ,
       0.21860462, 0.19999999, 0.4855814 , 0.40852708, 0.42480618,
       0.86046505, 1.        ], dtype=float32)

In [293]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, LSTM
from tensorflow import keras

In [294]:
model = Sequential()
model.add(LSTM(50, input_shape=(train_X.shape[1], train_X.shape[2])))
model.add(Dense(1))
model.compile(loss='mae', optimizer='adam')

In [295]:
history = model.fit(train_X, train_y, epochs=50, batch_size=72,validation_data=(test_X, test_y), verbose=2, shuffle=False)

Epoch 1/50
1/1 - 3s - loss: 0.1105 - val_loss: 0.3953 - 3s/epoch - 3s/step
Epoch 2/50
1/1 - 0s - loss: 0.1030 - val_loss: 0.3874 - 31ms/epoch - 31ms/step
Epoch 3/50
1/1 - 0s - loss: 0.0956 - val_loss: 0.3795 - 39ms/epoch - 39ms/step
Epoch 4/50
1/1 - 0s - loss: 0.0884 - val_loss: 0.3716 - 37ms/epoch - 37ms/step
Epoch 5/50
1/1 - 0s - loss: 0.0826 - val_loss: 0.3640 - 29ms/epoch - 29ms/step
Epoch 6/50
1/1 - 0s - loss: 0.0773 - val_loss: 0.3565 - 35ms/epoch - 35ms/step
Epoch 7/50
1/1 - 0s - loss: 0.0725 - val_loss: 0.3492 - 30ms/epoch - 30ms/step
Epoch 8/50
1/1 - 0s - loss: 0.0679 - val_loss: 0.3420 - 35ms/epoch - 35ms/step
Epoch 9/50
1/1 - 0s - loss: 0.0636 - val_loss: 0.3351 - 39ms/epoch - 39ms/step
Epoch 10/50
1/1 - 0s - loss: 0.0604 - val_loss: 0.3283 - 38ms/epoch - 38ms/step
Epoch 11/50
1/1 - 0s - loss: 0.0576 - val_loss: 0.3218 - 37ms/epoch - 37ms/step
Epoch 12/50
1/1 - 0s - loss: 0.0554 - val_loss: 0.3158 - 41ms/epoch - 41ms/step
Epoch 13/50
1/1 - 0s - loss: 0.0540 - val_loss: 0.310

In [296]:
print(test_X)

[[[0.14744186 0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.7203615
   0.3617885  0.20786512 0.        ]]

 [[0.18139535 0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.6529918
   0.57317066 0.3089888  0.        ]]

 [[0.1727907  0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.4619317
   0.69105697 0.49999988 0.        ]]

 [[0.15069765 0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.5222752
   0.9552846  0.5955056  0.        ]]

 [[0.16186047 0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.4900167
   0.4227643  0.3539325  0.        ]]

 [[0.1607973  0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.4688102
   0.43495917 0.3314606  0.    

In [297]:
train_y

array([0.10976744, 0.00620157, 0.        , 0.00465116, 0.04651165,
       0.0604651 , 0.01302326, 0.05116278, 0.03720927, 0.02325583,
       0.02325583, 0.09302324, 0.08682168, 0.11534882, 0.11627907,
       0.09488374, 0.14418602, 0.08139533, 0.0933333 , 0.11860466,
       0.12372094, 0.16279072, 0.16744184, 0.14744186], dtype=float32)

In [298]:
test_y

array([0.18139535, 0.1727907 , 0.15069765, 0.16186047, 0.1607973 ,
       0.21860462, 0.19999999, 0.4855814 , 0.40852708, 0.42480618,
       0.86046505, 1.        ], dtype=float32)

In [299]:
import numpy as np

In [300]:
from numpy import concatenate

In [301]:
yhat = model.predict(test_X)
test_X = test_X.reshape((test_X.shape[0], test_X.shape[2]))
# invert scaling for forecast


1/1 [==============================] - 1s 508ms/step


In [302]:
yhat

array([[0.08182646],
       [0.08049782],
       [0.07285269],
       [0.07351136],
       [0.0740146 ],
       [0.07371382],
       [0.07423764],
       [0.07320823],
       [0.06906497],
       [0.06682032],
       [0.06704737],
       [0.07366493]], dtype=float32)

In [303]:
test_X

array([[0.14744186, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.7203615 , 0.3617885 , 0.20786512, 0.        ],
       [0.18139535, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.6529918 , 0.57317066, 0.3089888 , 0.        ],
       [0.1727907 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.4619317 , 0.69105697, 0.49999988, 0.        ],
       [0.15069765, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.5222752 , 0.9552846 , 0.5955056 , 0.        ],
       [0.16186047, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.4900167 , 0.4227643 , 

In [304]:
inv_yhat = concatenate((yhat, test_X[:, 1:]), axis=1)
inv_yhat


array([[0.08182646, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.7203615 , 0.3617885 , 0.20786512, 0.        ],
       [0.08049782, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.6529918 , 0.57317066, 0.3089888 , 0.        ],
       [0.07285269, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.4619317 , 0.69105697, 0.49999988, 0.        ],
       [0.07351136, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.5222752 , 0.9552846 , 0.5955056 , 0.        ],
       [0.0740146 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.4900167 , 0.4227643 , 

In [305]:
inv_yhat = scaler.inverse_transform(inv_yhat)
inv_yhat


array([[6.12963438e+04, 2.01200000e+03, 2.21000000e+02, 2.59040999e+00,
        4.00000000e+00, 5.64261079e-02, 1.13171645e-01, 2.31107339e-01,
        1.26888365e-01, 3.67897481e-01, 1.75817907e-01, 6.20825768e+01,
        7.03999996e+00, 3.05999994e+00, 8.50000000e+01],
       [6.11535156e+04, 2.01200000e+03, 2.21000000e+02, 2.59040999e+00,
        4.00000000e+00, 5.64261079e-02, 1.13171645e-01, 2.31107339e-01,
        1.26888365e-01, 3.67897481e-01, 1.75817907e-01, 6.02223892e+01,
        7.55999994e+00, 3.24000001e+00, 8.50000000e+01],
       [6.03316641e+04, 2.01200000e+03, 2.21000000e+02, 2.59040999e+00,
        4.00000000e+00, 5.64261079e-02, 1.13171645e-01, 2.31107339e-01,
        1.26888365e-01, 3.67897481e-01, 1.75817907e-01, 5.49469109e+01,
        7.85000038e+00, 3.57999969e+00, 8.50000000e+01],
       [6.04024727e+04, 2.01200000e+03, 2.21000000e+02, 2.59040999e+00,
        4.00000000e+00, 5.64261079e-02, 1.13171645e-01, 2.31107339e-01,
        1.26888365e-01, 3.67897481e-0

In [306]:
inv_yhat = inv_yhat[:,0]

스케일러에서 원래대로 돌리기

In [307]:
test_y

array([0.18139535, 0.1727907 , 0.15069765, 0.16186047, 0.1607973 ,
       0.21860462, 0.19999999, 0.4855814 , 0.40852708, 0.42480618,
       0.86046505, 1.        ], dtype=float32)

In [308]:
inv_yhat

array([61296.344, 61153.516, 60331.664, 60402.473, 60456.57 , 60424.24 ,
       60480.547, 60369.883, 59924.484, 59683.184, 59707.59 , 60418.977],
      dtype=float32)

In [309]:
yhat

array([[0.08182646],
       [0.08049782],
       [0.07285269],
       [0.07351136],
       [0.0740146 ],
       [0.07371382],
       [0.07423764],
       [0.07320823],
       [0.06906497],
       [0.06682032],
       [0.06704737],
       [0.07366493]], dtype=float32)

In [310]:
from sklearn.metrics import mean_squared_error

In [311]:
import math
rmse = math.sqrt(mean_squared_error(inv_y, inv_yhat))
print(rmse)

7901.204971395186


In [312]:
#예측값
inv_y

array([52500., 52500., 52500., 52500., 52500., 52500., 52500., 52500.,
       52500., 52500., 52500., 52500.], dtype=float32)

In [313]:
inv_y.shape

(12,)

In [314]:
#실제값
inv_yhat

array([61296.344, 61153.516, 60331.664, 60402.473, 60456.57 , 60424.24 ,
       60480.547, 60369.883, 59924.484, 59683.184, 59707.59 , 60418.977],
      dtype=float32)

In [315]:
import matplotlib.pyplot as plt

In [316]:
test_y

array([0.18139535, 0.1727907 , 0.15069765, 0.16186047, 0.1607973 ,
       0.21860462, 0.19999999, 0.4855814 , 0.40852708, 0.42480618,
       0.86046505, 1.        ], dtype=float32)

In [317]:
test_y = test_y.reshape((len(test_y), 1))
test_y


array([[0.18139535],
       [0.1727907 ],
       [0.15069765],
       [0.16186047],
       [0.1607973 ],
       [0.21860462],
       [0.19999999],
       [0.4855814 ],
       [0.40852708],
       [0.42480618],
       [0.86046505],
       [1.        ]], dtype=float32)

In [318]:
inv_y = concatenate((test_y, test_X[:, 1:]), axis=1)
inv_y


array([[0.18139535, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.7203615 , 0.3617885 , 0.20786512, 0.        ],
       [0.1727907 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.6529918 , 0.57317066, 0.3089888 , 0.        ],
       [0.15069765, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.4619317 , 0.69105697, 0.49999988, 0.        ],
       [0.16186047, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.5222752 , 0.9552846 , 0.5955056 , 0.        ],
       [0.1607973 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.4900167 , 0.4227643 , 

In [319]:
inv_y = scaler.inverse_transform(inv_y)
inv_y


array([[7.20000000e+04, 2.01200000e+03, 2.21000000e+02, 2.59040999e+00,
        4.00000000e+00, 5.64261079e-02, 1.13171645e-01, 2.31107339e-01,
        1.26888365e-01, 3.67897481e-01, 1.75817907e-01, 6.20825768e+01,
        7.03999996e+00, 3.05999994e+00, 8.50000000e+01],
       [7.10750000e+04, 2.01200000e+03, 2.21000000e+02, 2.59040999e+00,
        4.00000000e+00, 5.64261079e-02, 1.13171645e-01, 2.31107339e-01,
        1.26888365e-01, 3.67897481e-01, 1.75817907e-01, 6.02223892e+01,
        7.55999994e+00, 3.24000001e+00, 8.50000000e+01],
       [6.87000000e+04, 2.01200000e+03, 2.21000000e+02, 2.59040999e+00,
        4.00000000e+00, 5.64261079e-02, 1.13171645e-01, 2.31107339e-01,
        1.26888365e-01, 3.67897481e-01, 1.75817907e-01, 5.49469109e+01,
        7.85000038e+00, 3.57999969e+00, 8.50000000e+01],
       [6.99000000e+04, 2.01200000e+03, 2.21000000e+02, 2.59040999e+00,
        4.00000000e+00, 5.64261079e-02, 1.13171645e-01, 2.31107339e-01,
        1.26888365e-01, 3.67897481e-0

In [320]:
inv_y = inv_y[:,0]

In [321]:
inv_y

array([ 72000.   ,  71075.   ,  68700.   ,  69900.   ,  69785.71 ,
        76000.   ,  74000.   , 104700.   ,  96416.664,  98166.664,
       145000.   , 160000.   ], dtype=float32)

In [323]:
inv_yhat

array([61296.344, 61153.516, 60331.664, 60402.473, 60456.57 , 60424.24 ,
       60480.547, 60369.883, 59924.484, 59683.184, 59707.59 , 60418.977],
      dtype=float32)